-- Create report_fixes table
CREATE TABLE IF NOT EXISTS public.report_fixes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_check_id BIGINT NOT NULL REFERENCES public.daily_checks(id) ON DELETE CASCADE,
  fix_notes TEXT NOT NULL,
  fixed_by TEXT NOT NULL,
  fixed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'fixed', 'wont_fix')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_report_fixes_daily_check_id ON public.report_fixes(daily_check_id);
CREATE INDEX IF NOT EXISTS idx_report_fixes_fixed_at ON public.report_fixes(fixed_at);

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_report_fixes_updated_at
BEFORE UPDATE ON public.report_fixes
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE public.report_fixes ENABLE ROW LEVEL SECURITY;

-- Add RLS policies
CREATE POLICY "Enable read access for all users"
ON public.report_fixes
FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Enable insert for authenticated users"
ON public.report_fixes
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
ON public.report_fixes
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Enable delete for authenticated users"
ON public.report_fixes
FOR DELETE
TO authenticated
USING (true);
