create table if not exists public.auto_checks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  website_id bigint not null references public.websites(id) on delete cascade,
  website_name text not null,
  website_url text not null,
  status_code integer,
  error_type text not null,
  response_time_ms integer,
  checked_at timestamptz not null default now(),
  is_live boolean not null
);

create index if not exists auto_checks_user_id_idx on public.auto_checks (user_id);
create index if not exists auto_checks_checked_at_idx on public.auto_checks (checked_at desc);
create index if not exists auto_checks_website_id_idx on public.auto_checks (website_id);

alter table public.auto_checks enable row level security;

create policy "auto_checks_select_own" on public.auto_checks
  for select using (auth.uid() = user_id);

create policy "auto_checks_insert_own" on public.auto_checks
  for insert with check (auth.uid() = user_id);

create policy "auto_checks_update_own" on public.auto_checks
  for update using (auth.uid() = user_id);

create policy "auto_checks_delete_own" on public.auto_checks
  for delete using (auth.uid() = user_id);
